db:
  vendor: mysql
  database: securedmvc

spring:
  profiles:
    active: dev
    #disabled-security

  datasource:
    url: jdbc:${db.vendor}://${db.host}/${db.database}
    username: ${db.user}
    password: ${db.pass}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true

    hibernate:
      ddl-auto: none


flyway:
  enabled: true
  locations: db/migration/${db.vendor}
  baseline-on-migrate: true
  baseline-version: 1
